name: quiz_game
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  get: 4.6.5
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.1.1
  intl: ^0.18.1
  lottie: ^2.3.2
  http: ^1.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/lotties/

